[package]
name = "term-svg"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
bytecount = "0.6.2"
handlebars = "3.5.4"
os_pipe = "0.9.2"
serde = { version = "1.0", features = ["derive"] }
quick-xml = "0.22.0"
pretty_assertions = { version = "0.7.2", optional = true }
termcolor = "1.1.2"

[dev-dependencies]
anyhow = "1.0.40"
assert_cmd = "1.0.3"
assert_matches = "1.5.0"

[features]
default = ["pretty_assertions"]
