[package]
name = "term-transcript-cli"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[[bin]]
name = "term-transcript"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.40"
atty = "0.2.14"
structopt = "0.3.21"
pretty_assertions = "0.7.2"
termcolor = "1.1.2"
textwrap = "0.11"

term-transcript = { version = "0.1.0", path = ".." }
