[package]
name = "term-transcript-cli"
version = "0.2.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2021"
rust-version = "1.61"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["snapshot", "terminal", "SVG"]
categories = ["command-line-utilities", "development-tools::testing", "visualization"]
description = "CLI wrapper for term-transcript"
repository = "https://github.com/slowli/term-transcript"

[[bin]]
name = "term-transcript"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.40"
atty = "0.2.14"
clap = { version = "4.0.30", features = ["derive", "env", "wrap_help"] }
handlebars = "4.3.1"
serde_json = "1.0"
termcolor = "1.1.2"

term-transcript = { version = "0.2.0", path = ".." }

[dev-dependencies]
tempfile = "3.2.0"

[features]
# Enables capturing output via pseudo-terminal (PTY).
portable-pty = ["term-transcript/portable-pty"]

[workspace]
# Separate workspace since we need a lockfile
