[package]
name = "term-transcript-cli"
version = "0.1.0"
authors = ["Alex Ostrovski <ostrovski.alex@gmail.com>"]
edition = "2018"
readme = "README.md"
license = "MIT OR Apache-2.0"
keywords = ["snapshot", "terminal", "SVG"]
categories = ["command-line-utilities", "development-tools::testing", "visualization"]
description = "CLI wrapper for term-transcript"
repository = "https://github.com/slowli/term-transcript"

[[bin]]
name = "term-transcript"
path = "src/main.rs"

[dependencies]
anyhow = "1.0.40"
atty = "0.2.14"
clap = "2.33.3"
structopt = { version = "0.3.21", features = ["color", "wrap_help"] }
termcolor = "1.1.2"

term-transcript = { version = "0.1.0", path = ".." }

[features]
# Enables capturing output via pseudo-terminal (PTY).
portable-pty = ["term-transcript/portable-pty"]
